spring:
  spofiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: txservicecloud-config-tx-dev
---
spring:
  profiles: test
  application:
    name: txservicecloud-config-tx-test
